version: "3"
services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    restart: always
    command: npm start
    volumes:
      - ./:/src
      - /node_modules/
      - /backend/
    depends_on:
      - backend
      - mongodb
    environment:
      - SKIP_PREFLIGHT_CHECK:true
      - HOST=0.0.0.0

  backend:
    build: ./backend/
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/src/backend
      - /src/backend/node_modules/
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    command: npm start
    restart: always
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
      MONGO_DB: "mongodb://mongodb:27017/irrigation"

  mongodb:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    restart: always
