version: "3"
services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    restart: always
    command: npm start
    volumes:
      - ./:/src
      - /node_modules/
      - /backend/
    depends_on:
      - backend
      - mongodb
    environment:
      - SKIP_PREFLIGHT_CHECK:true
      - PORT:4200
      - HOST=0.0.0.0
      - "REACT_APP_BACKEND_URL=http://10.0.0.2:3000"

  backend:
    build: ./backend/
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/src/backend
      - /src/backend/node_modules/
    command: npm start
    restart: always
    labels:
      docker-mdns.enable: "true"
      docker-mdns.host: "irrigationbackend.local"
    depends_on:
      - mongodb
    environment:
      MONGO_DB: "mongodb://mongodb/irrigation"

  mongodb:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27018:27017"
    restart: always
