version: "3"
services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    restart: always
    command: npm start
    volumes:
      - ./:/src
      - /node_modules/
      - /backend/
    depends_on:
      - backend
      - mongodb
    environment:
      - SKIP_PREFLIGHT_CHECK:true
      - PORT:4200
      - HOST=0.0.0.0
      - "REACT_APP_BACKEND_URL=http://10.0.0.2:3000"

  backend:
    build: ./backend/
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/src/backend
      - /src/backend/node_modules/
    command: npm start
    restart: always
    labels:
      docker-mdns.enable: "true"
      docker-mdns.host: "irrigationbackend.local"
    depends_on:
      - mongodb
      - mdns
    environment:
      MONGO_DB: "mongodb://mongodb/irrigation"

  mongodb:
    image: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27018:27017"
    restart: always

  mdns:
    container_name: "docker-mdns"
    image: "phyber/docker-mdns:aarch64-latest"

    # We need to be able to see the real IP addresses on the host, so we need
    # host networking mode.
    network_mode: "host"

    # Set this to the name of the interface with the IP addresses you'd like to
    # announce for your hostnames.
    # Both IPv4 and IPv6 addresses will be used.
    command:
      - "eth0"

    # We need to be able to read docker.sock to watch for container events,
    # and we need to be able to write to the system d-bus socket to add
    # hostnames in Avahi
    volumes:
      - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
